[package]
name = "tako"
version = "0.0.0"
authors = [
  "Arian van Putten <aeroboy94@gmail.com>",
  "Ruud van Asseldonk <dev@veniogames.com>",
  "Tako Marks <me@tako.mx>"
]

[dependencies]
base64       = "0.9.0"
futures      = "0.1.21"
hyper        = "0.11.25"
hyper-rustls = "0.12.0"
tokio-core   = "0.1.17"
