[package]
name = "tako"
version = "0.0.0"
authors = [
  "Arian van Putten <aeroboy94@gmail.com>",
  "Ruud van Asseldonk <dev@veniogames.com>",
  "Tako Marks <me@tako.mx>"
]

[dependencies]
base64     = "0.9.0"
ring       = "0.13.0-alpha"
untrusted  = "0.6.1"
# TODO: Release a new version of Filebuffer with winapi dependency bumped,
# so we don't end up with two versions of transitive dependencies in the lock
# file.
filebuffer = "0.3.0"
